version: '2'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mysql
    ports:
      - "8000:80"
    volumes:
      - ./app/:/app/
      - ./:/docker/
    volumes_from:
      - storage
    networks:
      - php-network
#######################################
# MySQL server
#######################################
  mysql:
    build:
      context: docker/mysql/
      dockerfile: MySQL-5.7.Dockerfile
    restart: always
    volumes_from:
      - storage
    env_file:
      - etc/environment.yml
    networks:
    - php-network
#######################################
# PHP MY ADMIN
#######################################
  myphpadmin:
    build:
      context: docker/myphpadmin
      dockerfile: Dockerfile
    restart: always
    links:
    - mysql
    ports:
    - 8080:80
    environment:
    - PMA_ARBITRARY=1
	- PMA_HOST: mysql
    - PMA_PORT: 3306
    networks:
    - php-network

  storage:
    build:
      context: docker/storage/
    volumes:
      - /storage

networks:
    php-network:
      driver: bridge